# ------------------------------------------------------

# tools from download urls OTHER than github.com/glue-tools:
# get_win8key

# this tool is windows only
[[redirects]]
  from = "https://glue.tools/get_win8key/windows/*"
  to = "https://github.com/christian-korneck/get_win8key/raw/master/get_win8key.exe"
  status = 301
  force = true
# ------------------------------------------------------

# tools from s3:
# namesgen

[[redirects]]
  from = "https://glue.tools/namesgen/linux/64"
  to = "https://gluetools.s3.us-west-000.backblazeb2.com/namesgen_linux_amd64"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/namesgen/linux/amd64"
  to = "https://gluetools.s3.us-west-000.backblazeb2.com/namesgen_linux_amd64"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/namesgen/linux/32"
  to = "https://gluetools.s3.us-west-000.backblazeb2.com/namesgen_linux_386"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/namesgen/linux/386"
  to = "https://gluetools.s3.us-west-000.backblazeb2.com/namesgen_linux_386"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/namesgen/linux/arm64"
  to = "https://gluetools.s3.us-west-000.backblazeb2.com/namesgen_linux_arm64"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/namesgen/linux/arm32"
  to = "https://gluetools.s3.us-west-000.backblazeb2.com/namesgen_linux_arm"
  status = 301
  force = true

# default for Linux: amd64 (typical cloud vm)
[[redirects]]
  from = "https://glue.tools/namesgen/linux"
  to = "https://gluetools.s3.us-west-000.backblazeb2.com/namesgen_linux_amd64"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/namesgen/mac/64"
  to = "https://gluetools.s3.us-west-000.backblazeb2.com/namesgen_darwin_amd64"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/namesgen/mac/arm64"
  to = "https://gluetools.s3.us-west-000.backblazeb2.com/namesgen_darwin_arm64"
  status = 301
  force = true

# default for Mac: universal2 (it just works)
[[redirects]]
  from = "https://glue.tools/namesgen/mac"
  to = "https://gluetools.s3.us-west-000.backblazeb2.com/namesgen_darwin_universal2"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/namesgen/windows/64"
  to = "https://gluetools.s3.us-west-000.backblazeb2.com/namesgen_windows_amd64.exe"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/namesgen/windows/amd64"
  to = "https://gluetools.s3.us-west-000.backblazeb2.com/namesgen_windows_amd64.exe"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/namesgen/windows/32"
  to = "https://gluetools.s3.us-west-000.backblazeb2.com/namesgen_windows_386.exe"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/namesgen/windows/386"
  to = "https://gluetools.s3.us-west-000.backblazeb2.com/namesgen_windows_386.exe"
  status = 301
  force = true

# default for windows: amd64 (so it runs in 64-bit only nanoserver)
[[redirects]]
  from = "https://glue.tools/namesgen/windows"
  to = "https://gluetools.s3.us-west-000.backblazeb2.com/namesgen_windows_amd64.exe"
  status = 301
  force = true


# ------------------------------------------------------

# tools from download urls OTHER than github.com/glue-tools:
# getignore

[[redirects]]
  from = "https://glue.tools/getignore/linux/64"
  to = "https://github.com/christian-korneck/getignore/releases/latest/download/getignore_linux_amd64"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/getignore/linux/amd64"
  to = "https://github.com/christian-korneck/getignore/releases/latest/download/getignore_linux_amd64"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/getignore/linux/32"
  to = "https://github.com/christian-korneck/getignore/releases/latest/download/getignore_linux_386"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/getignore/linux/386"
  to = "https://github.com/christian-korneck/getignore/releases/latest/download/getignore_linux_386"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/getignore/linux/arm64"
  to = "https://github.com/christian-korneck/getignore/releases/latest/download/getignore_linux_arm64"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/getignore/linux/arm32"
  to = "https://github.com/christian-korneck/getignore/releases/latest/download/getignore_linux_arm"
  status = 301
  force = true

# default for Linux: amd64 (typical cloud vm)
[[redirects]]
  from = "https://glue.tools/getignore/linux"
  to = "https://github.com/christian-korneck/getignore/releases/latest/download/getignore_linux_amd64"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/getignore/mac/64"
  to = "https://github.com/christian-korneck/getignore/releases/latest/download/getignore_darwin_amd64"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/getignore/mac/arm64"
  to = "https://github.com/christian-korneck/getignore/releases/latest/download/getignore_darwin_arm64"
  status = 301
  force = true

# default for Mac: universal2 (it just works)
[[redirects]]
  from = "https://glue.tools/getignore/mac"
  to = "https://github.com/christian-korneck/getignore/releases/latest/download/getignore_darwin_universal2"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/getignore/windows/64"
  to = "https://github.com/christian-korneck/getignore/releases/latest/download/getignore_windows_amd64.exe"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/getignore/windows/amd64"
  to = "https://github.com/christian-korneck/getignore/releases/latest/download/getignore_windows_amd64.exe"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/getignore/windows/32"
  to = "https://github.com/christian-korneck/getignore/releases/latest/download/getignore_windows_386.exe"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/getignore/windows/386"
  to = "https://github.com/christian-korneck/getignore/releases/latest/download/getignore_windows_386.exe"
  status = 301
  force = true

# default for windows: amd64 (so it runs in 64-bit only nanoserver)
[[redirects]]
  from = "https://glue.tools/getignore/windows"
  to = "https://github.com/christian-korneck/getignore/releases/latest/download/getignore_windows_amd64.exe"
  status = 301
  force = true

# ------------------------------------------------------

# tools from download urls OTHER than github.com/glue-tools:
# captive

[[redirects]]
  from = "https://glue.tools/captive/linux/64"
  to = "https://github.com/christian-korneck/captive/releases/latest/download/captive_linux_amd64"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/captive/linux/amd64"
  to = "https://github.com/christian-korneck/captive/releases/latest/download/captive_linux_amd64"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/captive/linux/32"
  to = "https://github.com/christian-korneck/captive/releases/latest/download/captive_linux_386"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/captive/linux/386"
  to = "https://github.com/christian-korneck/captive/releases/latest/download/captive_linux_386"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/captive/linux/arm64"
  to = "https://github.com/christian-korneck/captive/releases/latest/download/captive_linux_arm64"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/captive/linux/arm32"
  to = "https://github.com/christian-korneck/captive/releases/latest/download/captive_linux_arm"
  status = 301
  force = true

# default for Linux: amd64 (typical cloud vm)
[[redirects]]
  from = "https://glue.tools/captive/linux"
  to = "https://github.com/christian-korneck/captive/releases/latest/download/captive_linux_amd64"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/captive/mac/64"
  to = "https://github.com/christian-korneck/captive/releases/latest/download/captive_darwin_amd64"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/captive/mac/arm64"
  to = "https://github.com/christian-korneck/captive/releases/latest/download/captive_darwin_arm64"
  status = 301
  force = true

# default for Mac: universal2 (it just works)
[[redirects]]
  from = "https://glue.tools/captive/mac"
  to = "https://github.com/christian-korneck/captive/releases/latest/download/captive_darwin_universal2"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/captive/windows/64"
  to = "https://github.com/christian-korneck/captive/releases/latest/download/captive_windows_amd64.exe"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/captive/windows/amd64"
  to = "https://github.com/christian-korneck/captive/releases/latest/download/captive_windows_amd64.exe"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/captive/windows/32"
  to = "https://github.com/christian-korneck/captive/releases/latest/download/captive_windows_386.exe"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/captive/windows/386"
  to = "https://github.com/christian-korneck/captive/releases/latest/download/captive_windows_386.exe"
  status = 301
  force = true

# default for windows: amd64 (so it runs in 64-bit only nanoserver)
[[redirects]]
  from = "https://glue.tools/captive/windows"
  to = "https://github.com/christian-korneck/captive/releases/latest/download/captive_windows_amd64.exe"
  status = 301
  force = true

# ------------------------------------------------------

# tools from download urls OTHER than github.com/glue-tools:
# docker-pushrm

[[redirects]]
  from = "https://glue.tools/docker-pushrm/linux/64"
  to = "https://github.com/christian-korneck/docker-pushrm/releases/latest/download/docker-pushrm_linux_amd64"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/docker-pushrm/linux/amd64"
  to = "https://github.com/christian-korneck/docker-pushrm/releases/latest/download/docker-pushrm_linux_amd64"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/docker-pushrm/linux/32"
  to = "https://github.com/christian-korneck/docker-pushrm/releases/latest/download/docker-pushrm_linux_386"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/docker-pushrm/linux/386"
  to = "https://github.com/christian-korneck/docker-pushrm/releases/latest/download/docker-pushrm_linux_386"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/docker-pushrm/linux/arm64"
  to = "https://github.com/christian-korneck/docker-pushrm/releases/latest/download/docker-pushrm_linux_arm64"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/docker-pushrm/linux/arm32"
  to = "https://github.com/christian-korneck/docker-pushrm/releases/latest/download/docker-pushrm_linux_arm"
  status = 301
  force = true

# default for Linux: amd64 (typical cloud vm)
[[redirects]]
  from = "https://glue.tools/docker-pushrm/linux"
  to = "https://github.com/christian-korneck/docker-pushrm/releases/latest/download/docker-pushrm_linux_amd64"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/docker-pushrm/mac/64"
  to = "https://github.com/christian-korneck/docker-pushrm/releases/latest/download/docker-pushrm_darwin_amd64"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/docker-pushrm/mac/arm64"
  to = "https://github.com/christian-korneck/docker-pushrm/releases/latest/download/docker-pushrm_darwin_arm64"
  status = 301
  force = true

# default for Mac: universal2 (it just works)
[[redirects]]
  from = "https://glue.tools/docker-pushrm/mac"
  to = "https://github.com/christian-korneck/docker-pushrm/releases/latest/download/docker-pushrm_darwin_universal2"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/docker-pushrm/windows/64"
  to = "https://github.com/christian-korneck/docker-pushrm/releases/latest/download/docker-pushrm_windows_amd64.exe"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/docker-pushrm/windows/amd64"
  to = "https://github.com/christian-korneck/docker-pushrm/releases/latest/download/docker-pushrm_windows_amd64.exe"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/docker-pushrm/windows/32"
  to = "https://github.com/christian-korneck/docker-pushrm/releases/latest/download/docker-pushrm_windows_386.exe"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/docker-pushrm/windows/386"
  to = "https://github.com/christian-korneck/docker-pushrm/releases/latest/download/docker-pushrm_windows_386.exe"
  status = 301
  force = true

# default for windows: amd64 (so it runs in 64-bit only nanoserver)
[[redirects]]
  from = "https://glue.tools/docker-pushrm/windows"
  to = "https://github.com/christian-korneck/docker-pushrm/releases/latest/download/docker-pushrm_windows_amd64.exe"
  status = 301
  force = true

# ------------------------------------------------------

# tool download redirects to github releases
# for github.com/glue-tools

[[redirects]]
  from = "https://glue.tools/:tool/linux/64"
  to = "https://github.com/glue-tools/:tool/releases/latest/download/:tool_linux_amd64"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/:tool/linux/amd64"
  to = "https://github.com/glue-tools/:tool/releases/latest/download/:tool_linux_amd64"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/:tool/linux/32"
  to = "https://github.com/glue-tools/:tool/releases/latest/download/:tool_linux_386"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/:tool/linux/386"
  to = "https://github.com/glue-tools/:tool/releases/latest/download/:tool_linux_386"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/:tool/linux/arm64"
  to = "https://github.com/glue-tools/:tool/releases/latest/download/:tool_linux_arm64"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/:tool/linux/arm32"
  to = "https://github.com/glue-tools/:tool/releases/latest/download/:tool_linux_arm"
  status = 301
  force = true

# default for Linux: amd64 (typical cloud vm)
[[redirects]]
  from = "https://glue.tools/:tool/linux"
  to = "https://github.com/glue-tools/:tool/releases/latest/download/:tool_linux_amd64"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/:tool/mac/64"
  to = "https://github.com/glue-tools/:tool/releases/latest/download/:tool_darwin_amd64"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/:tool/mac/arm64"
  to = "https://github.com/glue-tools/:tool/releases/latest/download/:tool_darwin_arm64"
  status = 301
  force = true

# default for Mac: universal2 (it just works)
[[redirects]]
  from = "https://glue.tools/:tool/mac"
  to = "https://github.com/glue-tools/:tool/releases/latest/download/:tool_darwin_universal2"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/:tool/windows/64"
  to = "https://github.com/glue-tools/:tool/releases/latest/download/:tool_windows_amd64.exe"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/:tool/windows/amd64"
  to = "https://github.com/glue-tools/:tool/releases/latest/download/:tool_windows_amd64.exe"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/:tool/windows/32"
  to = "https://github.com/glue-tools/:tool/releases/latest/download/:tool_windows_386.exe"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/:tool/windows/386"
  to = "https://github.com/glue-tools/:tool/releases/latest/download/:tool_windows_386.exe"
  status = 301
  force = true

# default for windows: amd64 (so it runs in 64-bit only nanoserver)
[[redirects]]
  from = "https://glue.tools/:tool/windows"
  to = "https://github.com/glue-tools/:tool/releases/latest/download/:tool_windows_amd64.exe"
  status = 301
  force = true


# ------------------------------------------------------

# tool project page redirect - overwrites

[[redirects]]
  from = "https://glue.tools/docker-pushrm"
  to = "https://github.com/christian-korneck/docker-pushrm"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/getignore"
  to = "https://github.com/christian-korneck/getignore"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/captive"
  to = "https://github.com/christian-korneck/captive"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/get_win8key"
  to = "https://github.com/christian-korneck/get_win8key"
  status = 301
  force = true

# ------------------------------------------------------

# tool project page redirect - github.com/glue-tools/*

[[redirects]]
  from = "https://glue.tools/:tool"
  to = "https://github.com/glue-tools/:tool"
  status = 301
  force = false

# ------------------------------------------------------

# os shortcuts/aliases
[[redirects]]
  from = "https://glue.tools/:tool/win/*"
  to = "https://glue.tools/:tool/windows/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/:tool/elf/*"
  to = "https://glue.tools/:tool/linux/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/:tool/darwin/*"
  to = "https://glue.tools/:tool/mac/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://glue.tools/:tool/macos/*"
  to = "https://glue.tools/:tool/mac/:splat"
  status = 301
  force = true

# ------------------------------------------------------

# default redirects (http->https, www->@)

[[redirects]]
  from = "https://www.glue.tools/*"
  to = "https://glue.tools/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://glue.tools/*"
  to = "https://glue.tools/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.glue.tools/*"
  to = "https://glue.tools/:splat"
  status = 301
  force = true


